import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomNavbar from "./components/BottomNavbar/BottomNavbar";
import SearchBar from "./components/SearchBar/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-arp="">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased bg-[#a4d7f59c] min-h-screen pb-16 md:pb-0`}
      >
        <div className="max-w-md mx-auto bg-white min-h-screen relative ">
          <SearchBar />
          <div className="px-3">
            {children}
          </div>
          <BottomNavbar />
        </div>
      </body>
    </html>
  );
}